//! Disk-usage statistics and cleanup for session/run log files.
//!
//! `get_storage_stats` measures how much disk space the log files generated by
//! Devdy runs and the mirrored Claude/Codex CLI sessions occupy, grouped into
//! categories. `clean_storage` deletes the log files for a single category to
//! reclaim that space.
//!
//! Devdy run logs live at `<project>/.devdy/runs/<run_id>.log`; cleaning them
//! removes the files only — the `runs` rows and the `run_usage` ledger are kept,
//! so run history (and token stats) survive, just without the raw transcript.
//! Claude/Codex categories cover the CLI's own session stores
//! (`~/.claude/projects/**/*.jsonl`, `~/.codex/sessions/**/*.jsonl`); deleting
//! those is destructive to the CLI's history, which is why they are flagged.

use crate::db::Db;
use serde::Serialize;
use sqlx::Row;
use std::path::{Path, PathBuf};
use tauri::State;
use walkdir::WalkDir;

/// Stable identifiers shared with the frontend cleanup action.
const CAT_DEVDY: &str = "devdy_logs";
const CAT_CLAUDE: &str = "claude_sessions";
const CAT_CODEX: &str = "codex_sessions";

#[derive(Debug, Serialize)]
pub struct StorageCategory {
    /// One of `devdy_logs` | `claude_sessions` | `codex_sessions`.
    pub id: String,
    pub label: String,
    pub description: String,
    /// Representative location shown in the UI (may stand for several roots).
    pub path: String,
    pub size_bytes: u64,
    pub file_count: u64,
    /// False when no matching files exist (nothing to clean).
    pub deletable: bool,
    /// True when cleaning loses history outside Devdy's own database (the CLI
    /// session stores). Devdy run logs are non-destructive: records are kept.
    pub destructive: bool,
}

#[derive(Debug, Serialize)]
pub struct StorageStats {
    pub categories: Vec<StorageCategory>,
    pub total_bytes: u64,
    pub total_files: u64,
}

#[derive(Debug, Serialize)]
pub struct CleanResult {
    pub category: String,
    pub deleted_files: u64,
    pub freed_bytes: u64,
}

fn home() -> Option<PathBuf> {
    std::env::var("HOME").ok().map(PathBuf::from)
}

/// `.jsonl` transcript predicate used by both Claude and Codex session stores.
fn is_jsonl(p: &Path) -> bool {
    p.extension().map(|e| e == "jsonl").unwrap_or(false)
}

/// `.log` predicate for Devdy run output files.
fn is_log(p: &Path) -> bool {
    p.extension().map(|e| e == "log").unwrap_or(false)
}

/// Walk `root`, summing size and count of regular files matching `pred`.
/// Missing roots contribute nothing. Symlinks are not followed.
fn scan<P: Fn(&Path) -> bool>(root: &Path, pred: &P) -> (u64, u64) {
    let mut bytes = 0u64;
    let mut count = 0u64;
    for entry in WalkDir::new(root).follow_links(false).into_iter().filter_map(|e| e.ok()) {
        if entry.file_type().is_file() && pred(entry.path()) {
            if let Ok(meta) = entry.metadata() {
                bytes += meta.len();
                count += 1;
            }
        }
    }
    (bytes, count)
}

/// Delete every regular file under `root` matching `pred`, returning the freed
/// bytes and file count. Best-effort: unreadable/undeletable files are skipped.
fn purge<P: Fn(&Path) -> bool>(root: &Path, pred: &P) -> (u64, u64) {
    let mut bytes = 0u64;
    let mut count = 0u64;
    for entry in WalkDir::new(root).follow_links(false).into_iter().filter_map(|e| e.ok()) {
        if entry.file_type().is_file() && pred(entry.path()) {
            let len = entry.metadata().map(|m| m.len()).unwrap_or(0);
            if std::fs::remove_file(entry.path()).is_ok() {
                bytes += len;
                count += 1;
            }
        }
    }
    (bytes, count)
}

/// Every project's `.devdy/runs` directory (the only place Devdy writes logs).
async fn devdy_runs_dirs(db: &Db) -> Vec<PathBuf> {
    let rows = match sqlx::query("SELECT path FROM projects").fetch_all(db).await {
        Ok(r) => r,
        Err(_) => return Vec::new(),
    };
    rows.into_iter()
        .filter_map(|row| row.try_get::<String, _>("path").ok())
        .map(|p| Path::new(&p).join(".devdy").join("runs"))
        .collect()
}

#[tauri::command]
pub async fn get_storage_stats(db: State<'_, Db>) -> Result<StorageStats, String> {
    // Devdy run logs — sum *.log across every project's .devdy/runs.
    let mut devdy_bytes = 0u64;
    let mut devdy_files = 0u64;
    for dir in devdy_runs_dirs(db.inner()).await {
        let (b, c) = scan(&dir, &is_log);
        devdy_bytes += b;
        devdy_files += c;
    }

    // Claude/Codex CLI session transcripts.
    let (claude_bytes, claude_files) = match home() {
        Some(h) => scan(&h.join(".claude").join("projects"), &is_jsonl),
        None => (0, 0),
    };
    let (codex_bytes, codex_files) = match home() {
        Some(h) => scan(&h.join(".codex").join("sessions"), &is_jsonl),
        None => (0, 0),
    };

    let categories = vec![
        StorageCategory {
            id: CAT_DEVDY.into(),
            label: "Devdy run logs".into(),
            description: "Log output of runs in every project (.devdy/runs/*.log). \
                          Cleaning keeps run history and token stats — only the raw \
                          transcript files are removed."
                .into(),
            path: "<project>/.devdy/runs".into(),
            size_bytes: devdy_bytes,
            file_count: devdy_files,
            deletable: devdy_files > 0,
            destructive: false,
        },
        StorageCategory {
            id: CAT_CLAUDE.into(),
            label: "Claude CLI sessions".into(),
            description: "Claude Code session transcripts (~/.claude/projects/**/*.jsonl). \
                          Shared with the CLI/VS Code — deleting removes that history."
                .into(),
            path: "~/.claude/projects".into(),
            size_bytes: claude_bytes,
            file_count: claude_files,
            deletable: claude_files > 0,
            destructive: true,
        },
        StorageCategory {
            id: CAT_CODEX.into(),
            label: "Codex CLI sessions".into(),
            description: "Codex rollout session logs (~/.codex/sessions/**/*.jsonl). \
                          Shared with the Codex CLI — deleting removes that history."
                .into(),
            path: "~/.codex/sessions".into(),
            size_bytes: codex_bytes,
            file_count: codex_files,
            deletable: codex_files > 0,
            destructive: true,
        },
    ];

    let total_bytes = categories.iter().map(|c| c.size_bytes).sum();
    let total_files = categories.iter().map(|c| c.file_count).sum();

    Ok(StorageStats {
        categories,
        total_bytes,
        total_files,
    })
}

#[tauri::command]
pub async fn clean_storage(db: State<'_, Db>, category: String) -> Result<CleanResult, String> {
    let (mut freed, mut deleted) = (0u64, 0u64);

    match category.as_str() {
        CAT_DEVDY => {
            for dir in devdy_runs_dirs(db.inner()).await {
                let (b, c) = purge(&dir, &is_log);
                freed += b;
                deleted += c;
            }
        }
        CAT_CLAUDE => {
            if let Some(h) = home() {
                let (b, c) = purge(&h.join(".claude").join("projects"), &is_jsonl);
                freed += b;
                deleted += c;
            }
        }
        CAT_CODEX => {
            if let Some(h) = home() {
                let (b, c) = purge(&h.join(".codex").join("sessions"), &is_jsonl);
                freed += b;
                deleted += c;
            }
        }
        other => return Err(format!("unknown storage category: {other}")),
    }

    Ok(CleanResult {
        category,
        deleted_files: deleted,
        freed_bytes: freed,
    })
}
